"""
Storage Service for CV File Upload/Download.

Provides abstraction for file storage operations.
Supports:
- Local filesystem storage (development)
- Cloud storage (S3/GCS) for production

Files are stored with system-generated names, never exposing original filenames.
"""
from __future__ import annotations

import os
import shutil
from pathlib import Path
from typing import BinaryIO


def _env_str(name: str, default: str = "") -> str:
    return str(os.getenv(name, default) or default).strip()


def _get_storage_type() -> str:
    """Get storage type from env: 'local', 's3', or 'gcs'."""
    return _env_str("STORAGE_TYPE", "local").lower()


def _get_local_storage_path() -> Path:
    """Get local storage directory path."""
    path = _env_str("LOCAL_STORAGE_PATH", "uploads")
    p = Path(path)
    p.mkdir(parents=True, exist_ok=True)
    return p


# ============================================================================
# Local Storage Implementation
# ============================================================================

def _upload_local(key: str, data: bytes, content_type: str) -> None:
    """Upload file to local filesystem."""
    storage_path = _get_local_storage_path()
    file_path = storage_path / key
    file_path.parent.mkdir(parents=True, exist_ok=True)
    file_path.write_bytes(data)


def _download_local(key: str) -> tuple[bytes, str]:
    """Download file from local filesystem."""
    storage_path = _get_local_storage_path()
    file_path = storage_path / key
    
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {key}")
    
    # Guess content type from extension
    ext = file_path.suffix.lower()
    content_types = {
        ".pdf": "application/pdf",
        ".doc": "application/msword",
        ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    }
    content_type = content_types.get(ext, "application/octet-stream")
    
    return file_path.read_bytes(), content_type


def _delete_local(key: str) -> None:
    """Delete file from local filesystem."""
    storage_path = _get_local_storage_path()
    file_path = storage_path / key
    if file_path.exists():
        file_path.unlink()


# ============================================================================
# S3 Storage Implementation (placeholder)
# ============================================================================

def _upload_s3(key: str, data: bytes, content_type: str) -> None:
    """Upload file to S3 (requires boto3)."""
    import boto3
    
    bucket = _env_str("S3_BUCKET")
    if not bucket:
        raise RuntimeError("S3_BUCKET not configured")
    
    s3 = boto3.client("s3")
    s3.put_object(
        Bucket=bucket,
        Key=f"cv/{key}",
        Body=data,
        ContentType=content_type,
    )


def _download_s3(key: str) -> tuple[bytes, str]:
    """Download file from S3 (requires boto3)."""
    import boto3
    
    bucket = _env_str("S3_BUCKET")
    if not bucket:
        raise RuntimeError("S3_BUCKET not configured")
    
    s3 = boto3.client("s3")
    resp = s3.get_object(Bucket=bucket, Key=f"cv/{key}")
    
    return resp["Body"].read(), resp.get("ContentType", "application/octet-stream")


def _delete_s3(key: str) -> None:
    """Delete file from S3 (requires boto3)."""
    import boto3
    
    bucket = _env_str("S3_BUCKET")
    if not bucket:
        return
    
    s3 = boto3.client("s3")
    s3.delete_object(Bucket=bucket, Key=f"cv/{key}")


# ============================================================================
# Public API
# ============================================================================

def upload_file_to_storage(key: str, data: bytes, content_type: str = "application/octet-stream") -> None:
    """
    Upload a file to storage.
    
    Args:
        key: Unique storage key (generated by generate_cv_storage_key)
        data: File content as bytes
        content_type: MIME type of the file
    """
    storage_type = _get_storage_type()
    
    if storage_type == "s3":
        _upload_s3(key, data, content_type)
    else:
        _upload_local(key, data, content_type)


def get_file_from_storage(key: str) -> tuple[bytes, str]:
    """
    Download a file from storage.
    
    Args:
        key: Storage key
        
    Returns:
        Tuple of (file_data, content_type)
        
    Raises:
        FileNotFoundError if file doesn't exist
    """
    storage_type = _get_storage_type()
    
    if storage_type == "s3":
        return _download_s3(key)
    else:
        return _download_local(key)


def delete_file_from_storage(key: str) -> None:
    """
    Delete a file from storage.
    
    Args:
        key: Storage key
    """
    storage_type = _get_storage_type()
    
    if storage_type == "s3":
        _delete_s3(key)
    else:
        _delete_local(key)
